#!/bin/sh

# Merge the 'incoming' branch into 'master' using the 'incoming' branch
# as canonical during conflicts.
# HACK: This little guy will not shut up, have to manually silence him
git merge incoming --quiet --commit --no-edit -m "xeno-remote-merge" --strategy=recursive -X theirs > /dev/null 2>&1

# Look for any self-destruct messages
if [ -n "`git log --grep xeno-destruct`" ]; then
    # If we find them, remove the repository.
    # TODO: I'd feel better if there were a more reliable way to grab the repo
    # path, but the working directory of the hook should always be the repo
    # directory, so this should be okay.
    XENO_REPO=`pwd`
    rm -rf "$XENO_REPO"

    # HACK: On some linux systems, bash will not remove the parent directory of
    # this script on a first pass because it will appear to be non-empty.  I
    # don't know how to fix it, changing the working directory doesn't help.
    # So if it is still there, delete it.
    if [ -d "$XENO_REPO" ]; then
        rm -rf "$XENO_REPO"
    fi

    exit
fi
